services:
  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
      tags:
        - mini-blog-posts:1.0.0
    image: mini-blog-posts:1.0.0
    ports:
      - "4000:3000"
    environment:
      - EVENT_BUS_API_URL=http://event-bus:3000
      - SERVICE_VERSION=1.0.0
    depends_on:
      - event-bus
    networks:
      - microservices
    labels:
      - "version=1.0.0"
      - "service=posts"
  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
      tags:
        - mini-blog-event-bus:1.0.0
    image: mini-blog-event-bus:1.0.0
    ports:
      - "4005:3000"
    environment:
      - POSTS_API_URL=http://posts:3000
      - COMMENTS_API_URL=http://comments:3000
      - QUERY_API_URL=http://query:3000
      - MODERATION_API_URL=http://moderation:3000
      - SERVICE_VERSION=1.0.0
    networks:
      - microservices
    labels:
      - "version=1.0.0"
      - "service=event-bus"
  query:
    build:
      context: ./query
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
      tags:
        - mini-blog-query:1.0.0
    image: mini-blog-query:1.0.0
    ports:
      - "4002:3000"
    environment:
      - EVENT_BUS_API_URL=http://event-bus:3000
      - SERVICE_VERSION=1.0.0
    depends_on:
      - event-bus
    networks:
      - microservices
    labels:
      - "version=1.0.0"
      - "service=query"
  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
      tags:
        - mini-blog-comments:1.0.0
    image: mini-blog-comments:1.0.0
    ports:
      - "4001:3000"
    environment:
      - EVENT_BUS_API_URL=http://event-bus:3000
      - SERVICE_VERSION=1.0.0
    depends_on:
      - event-bus
    networks:
      - microservices
    labels:
      - "version=1.0.0"
      - "service=comments"
  moderation:
    build:
      context: ./moderation
      dockerfile: Dockerfile
      args:
        - VERSION=1.0.0
      tags:
        - mini-blog-moderation:1.0.0
    image: mini-blog-moderation:1.0.0
    ports:
      - "4003:3000"
    environment:
      - EVENT_BUS_API_URL=http://event-bus:3000
      - SERVICE_VERSION=1.0.0
    depends_on:
      - event-bus
    networks:
      - microservices
    labels:
      - "version=1.0.0"
      - "service=moderation"

networks:
  microservices:
    driver: bridge
